### ISSUE TITLE
Error on project generation

### ISSUE THREAD

**Issue by CMadison** [Wtower/generator-makrina#7]
Hi thanks for building creating this generator. I keep getting the following error message when I attempt to generate a project using "yo makrina" or "yo" then selecting Makrina from generator list. Any insight on how to resolve this would be greatly appreciated.

Error Message:

```
module.js:457
    throw err;
    ^

Error: Cannot find module '../../services/build-context'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-makrina/generators/app/index.js:8:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3) 
```

**Comment by Wtower** [comment]
Hello and thanks for taking the time to post this issue. 

I can see that you have globally installed the generator and you are not using nvm. Could you please post the following information:
- node.js version
- npm version

**Comment by CMadison** [comment]
1. node@v6.4.0
2. npm@3.10.3

**Comment by Wtower** [comment]
I have been able to reproduce this. I will fix it and make a new release right away. Thanks again for your contribution.

Technical explanation: the default yeoman `generator-generator` that was used to generate this project had a default `files` declaration in `package.json`, causing the entire `services` folder to be left out from the published package. The only workaround is to install manually.

**Comment by Wtower** [comment]
Version 0.3.0 is now available on npm, it should fix this issue.
